version: 2
jobs:
  build:

    working_directory: ~/BDD

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: bdd-{{ checksum "pom.xml" }}

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: bdd-{{ checksum "pom.xml" }}
